name: Release

on:
    push:
        branches: ["main"]

jobs:
    build:
        name: Build and release
        timeout-minutes: 15
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
                  persist-credentials: false

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.32.2

            - name: Run install
              run: pnpm install

            - name: Run build
              run: pnpm build

            - name: Release version
              run: pnpm semantic-release
